### PR TITLE
Show failing test for .class::before scenario

### PR DESCRIPTION
**Pull request by motdotla**
Started doing some local testing on our templates with html-preflight and the latest 1.x uglify. Looks like there is an edge bug with `.class::before`. 

Not solved yet, but this PR shows the failing test. Working on fix.

### CODE REVIEW

**Comment by motdotla** [comment]
Stack trace for extra info:

```
  1) HTMLUglify #process uglifies a class with a ::before:
     TypeError: Cannot read property '0' of null
      at getName (/Users/mot/code/rebelmail/html-uglify/node_modules/css-what/index.js:98:36)
      at parseSelector (/Users/mot/code/rebelmail/html-uglify/node_modules/css-what/index.js:181:12)
      at parse (/Users/mot/code/rebelmail/html-uglify/node_modules/css-what/index.js:81:16)
      at /Users/mot/code/rebelmail/html-uglify/lib/main.js:113:26
      at Array.forEach (native)
      at HTMLUglify.processRules (/Users/mot/code/rebelmail/html-uglify/lib/main.js:108:9)
      at Object.<anonymous> (/Users/mot/code/rebelmail/html-uglify/lib/main.js:150:11)
      at exports.each (/Users/mot/code/rebelmail/html-uglify/node_modules/cheerio/lib/api/traversing.js:294:24)
      at HTMLUglify.rewriteStyles (/Users/mot/code/rebelmail/html-uglify/lib/main.js:147:14)
      at HTMLUglify.process (/Users/mot/code/rebelmail/html-uglify/lib/main.js:162:12)
      at Context.<anonymous> (/Users/mot/code/rebelmail/html-uglify/test/main.js:225:29)
      at callFn (/Users/mot/code/rebelmail/html-uglify/node_modules/mocha/lib/runnable.js:266:21)
      at Test.Runnable.run (/Users/mot/code/rebelmail/html-uglify/node_modules/mocha/lib/runnable.js:259:7)
      at Runner.runTest (/Users/mot/code/rebelmail/html-uglify/node_modules/mocha/lib/runner.js:387:10)
      at /Users/mot/code/rebelmail/html-uglify/node_modules/mocha/lib/runner.js:470:12
      at next (/Users/mot/code/rebelmail/html-uglify/node_modules/mocha/lib/runner.js:312:14)
      at /Users/mot/code/rebelmail/html-uglify/node_modules/mocha/lib/runner.js:322:7
      at next (/Users/mot/code/rebelmail/html-uglify/node_modules/mocha/lib/runner.js:257:23)
      at Immediate._onImmediate (/Users/mot/code/rebelmail/html-uglify/node_modules/mocha/lib/runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by motdotla** [comment]
Ok, thoughts @devinus @elbuo8. 

Particularly, @devinus - looking for your blessing here. 

I've ripped out cssWhat.

I tried to dig into cssWhat, but the error is fairly tricky one to solve. I have the start of it here: https://github.com/fb55/css-what/pull/13

I've spent the last 1.5 hours trying to work through it. Maybe you want to take a look and try your hand.

**Comment by elbuo8** [comment]
Up to you guys.

**Comment by motdotla** [comment]
I'm at dinner for the next few hours. I wont be able to respond for a couple hours. 

It would help me if you would address the overall pull request and its purpose and we can more easily go from there.

**Comment by devinus** [comment]
:+1: 

If it's broke, then revert. I'm still concerned about the amount of CSS parsers our CSS has to pass, though.

**Comment by motdotla** [comment]
Ok, in total this PR discards cssWhat since it is currently broken for `::before` and `::after` pseudo selectors, and gets those working simply with our own code.

**Pull request merged**
